server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
    max-connections: 10000
    max-threads: 2000

##spring配置
spring:
  application:
    #注册到注册中心应用名
    name: fdvt-core
  ##cloud配置
  cloud:
    zookeeper:
      #注册到zookeeper注册中心的服务地址
      connect-string: localhost:2181
      discovery:
        #是否启动服务注册
        register: true
        enabled: true
        #zk唯一id的标识
        instance-id: 1
        instance-port: ${server.port}
        #zk根节点名称，默认/services
        root: /schedule
  #Redis配置
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
  ##数据源配置
  datasource:
    name: D1
    url: jdbc:sqlite:d1-core/D1.db
    username:
    password:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.sqlite.JDBC
    hikari:  # 全局hikariCP参数，所有值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        minimum-idle: 5
        maximum-pool-size: 15
        auto-commit: true
        idle-timeout: 30000
        pool-name: DatebookHikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1




