server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
    max-connections: 10000
    max-threads: 2000

##spring配置
spring:
  application:
    #注册到注册中心应用名
    name: d1-core
  ##数据源配置
  datasource:
    name: D1
    url: jdbc:sqlite:d1-core/D1.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC
    tomcat:
     jdbc-interceptors: org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer;org.apache.tomcat.jdbc.pool.interceptor.ResetAbandonedTimer
     test-while-idle: true
     test-on-borrow: true
     validation-query: select 1
     validation-interval: 34000
     test-on-return: true
     time-between-eviction-runs-millis: 34000
     min-evictable-idle-time-millis: 55000
     max-wait: 30000
     remove-abandoned-timeout: 1800
     log-abandoned: true
     remove-abandoned: true
     max-active: 30
     max-idle: 15
     min-idle: 5
     initial-size: 10



